'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowRight, Check, RotateCcw, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { CONFIG, QUIZ } from '@/lib/config'
import { useDemoStoreContext } from '@/lib/store'

export default function QuizPage() { const { state, ready, dispatch } = useDemoStoreContext(); const [step, setStep] = useState(0); const [selected, setSelected] = useState(''); const [checked, setChecked] = useState(false); const [score, setScore] = useState(0); const [final, setFinal] = useState(0); const [result, setResult] = useState(false)
  useEffect(() => { if (ready && (!state.learnerName || state.viewedHotspots.length < 3)) window.location.replace(state.learnerName ? '/scene' : '/') }, [ready, state.learnerName, state.viewedHotspots.length]); if (!ready || !state.learnerName) return <div className="loading-state">Loading quiz…</div>
  const q = QUIZ[step]; const need = Math.ceil((CONFIG.PASS_MARK_PERCENT / 100) * QUIZ.length); function check() { if (!selected || checked) return; setChecked(true); if (selected === q.answer) setScore((v) => Math.min(v + 1, step + 1)) } function next() { if (step < QUIZ.length - 1) { setStep(step + 1); setSelected(''); setChecked(false) } else { const finalScore = Math.round(((score + (selected === q.answer ? 1 : 0)) / QUIZ.length) * 100); dispatch({ lastScore: finalScore, attempts: state.attempts + 1, passed: finalScore >= CONFIG.PASS_MARK_PERCENT }); if (finalScore >= CONFIG.PASS_MARK_PERCENT) dispatch({ type: 'pass', score: finalScore }); setFinal(finalScore); setResult(true) } }
  if (result) { const passed = state.passed || final >= CONFIG.PASS_MARK_PERCENT; return <div className="center-page wrap"><div className={passed ? 'result-card passed' : 'result-card failed'}>{passed ? <Check className="result-icon" /> : <X className="result-icon" />}<p className="eyebrow">Quiz complete</p><h1>{passed ? 'You passed.' : 'Not quite yet.'}</h1><div className="score-big">{final}%</div><p>You got {Math.round((final / 100) * QUIZ.length)} of {QUIZ.length} correct. The pass mark is {CONFIG.PASS_MARK_PERCENT}%. {need} of {QUIZ.length} answers are needed to pass.</p>{passed ? <Link href="/certificate" className="button primary">View certificate <ArrowRight /></Link> : <div className="result-actions"><button className="button primary" onClick={() => { setStep(0); setSelected(''); setChecked(false); setScore(0); setResult(false) }}><RotateCcw /> Try again</button><Link href="/scene" className="text-link">Review the scene</Link></div>}</div></div> }
  return <div className="quiz-page wrap"><Link className="back-link" href="/scene"><ArrowLeft /> Back to scene</Link><div className="quiz-head"><p className="eyebrow">Step 2 of 3 · Question {step + 1} of {QUIZ.length}</p><h1>Check what you know</h1><p>Pass mark: {CONFIG.PASS_MARK_PERCENT}%. You need {need} of {QUIZ.length} answers.</p></div><div className="question-card"><fieldset><legend>{q.question}</legend><div className="options">{q.options.map((option) => <label key={option} className={selected === option ? 'option selected' : 'option'}><input type="radio" name="answer" value={option} checked={selected === option} onChange={() => !checked && setSelected(option)} /> <span>{option}</span>{checked && option === q.answer && <Check />}{checked && selected === option && option !== q.answer && <X />}</label>)}</div></fieldset>{checked && <div className={selected === q.answer ? 'feedback correct' : 'feedback incorrect'} role="status">{selected === q.answer ? <Check /> : <X />}<span><strong>{selected === q.answer ? 'Correct.' : 'Not correct.'}</strong> {q.reason}</span></div>}<div className="question-actions">{!checked ? <button className="button primary" disabled={!selected} onClick={check}>Check answer <ArrowRight /></button> : <button className="button primary" onClick={next}>{step === 2 ? 'See result' : 'Next question'} <ArrowRight /></button>}</div></div></div>
}
