'use client'

import { useEffect, useRef, useState } from 'react'
import Script from 'next/script'
import { Minus, MoveDown, MoveLeft, MoveRight, MoveUp, Plus } from 'lucide-react'
import { CONFIG, Hotspot } from '@/lib/config'

type Props = { onOpen: (hotspot: Hotspot) => void; onReady?: (api: { lookAt: (yaw: number, pitch: number) => void }) => void }
export default function PanoViewer({ onOpen, onReady }: Props) { const ref = useRef<HTMLDivElement>(null); const viewer = useRef<{ lookAt: (pitch: number, yaw: number, hfov?: number) => void; getYaw: () => number; getPitch: () => number; getHfov: () => number } | null>(null); const [failed, setFailed] = useState(false)
  useEffect(() => { onReady?.({ lookAt: (yaw, pitch) => viewer.current?.lookAt(pitch, yaw, viewer.current.getHfov()) }); return () => { viewer.current = null } }, [onReady])
  function init() { const pannellum = (window as Window & { pannellum?: { viewer: (el: HTMLDivElement, opts: Record<string, unknown>) => typeof viewer.current } }).pannellum; if (!pannellum || !ref.current) return; try { viewer.current = pannellum.viewer(ref.current, { type: CONFIG.PANO.TYPE, panorama: CONFIG.PANO.SRC, autoLoad: true, showControls: false, keyboardZoom: true, mouseZoom: true, compass: false, yaw: CONFIG.PANO.INITIAL_YAW, pitch: CONFIG.PANO.INITIAL_PITCH, hfov: CONFIG.PANO.INITIAL_HFOV, hotSpots: CONFIG.HOTSPOTS.map((spot) => ({ pitch: spot.pitch, yaw: spot.yaw, cssClass: 'atlas-hotspot', createTooltipFunc: (hotspot: HTMLElement) => { hotspot.setAttribute('aria-label', spot.label); hotspot.title = spot.label; }, clickHandlerFunc: () => onOpen(spot) })) }) as typeof viewer.current } catch { setFailed(true) } }
  function move(direction: string) { if (!viewer.current) return; const yaw = viewer.current.getYaw(); const pitch = viewer.current.getPitch(); const hfov = viewer.current.getHfov(); const delta = direction === 'left' ? -15 : direction === 'right' ? 15 : direction === 'up' ? 10 : -10; viewer.current.lookAt(direction === 'up' || direction === 'down' ? pitch + delta : pitch, direction === 'left' || direction === 'right' ? yaw + delta : yaw, hfov) }
  return <div className="viewer-wrap"><Script src="https://cdn.jsdelivr.net/npm/pannellum@2.5.6/build/pannellum.js" onLoad={init} onError={() => setFailed(true)} /><div ref={ref} className="pano" role="application" aria-label="360 warehouse scene. Drag to look around. Use arrow keys. Press plus or minus to zoom." />{failed && <div className="pano-error"><strong>Scene image failed to load.</strong><span>Fix the panorama path in lib/config.ts: {CONFIG.PANO.SRC}</span><small>The hotspot list stays available on the right.</small></div>}<div className="scene-controls" aria-label="Scene controls"><button onClick={() => move('left')} aria-label="Pan left"><MoveLeft /></button><button onClick={() => move('right')} aria-label="Pan right"><MoveRight /></button><button onClick={() => move('up')} aria-label="Pan up"><MoveUp /></button><button onClick={() => move('down')} aria-label="Pan down"><MoveDown /></button><button onClick={() => viewer.current?.lookAt(viewer.current.getPitch(), viewer.current.getYaw(), viewer.current.getHfov() - 10)} aria-label="Zoom in"><Plus /></button><button onClick={() => viewer.current?.lookAt(viewer.current.getPitch(), viewer.current.getYaw(), viewer.current.getHfov() + 10)} aria-label="Zoom out"><Minus /></button></div><p className="scene-hint">Drag to look around. Use arrow keys. Press + or - to zoom.</p></div>
}
