'use client'

import { Check, ChevronDown, Search, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import { formatDate } from '@/lib/config'
import { useDemoStoreContext } from '@/lib/store'

export default function ManagerPage() { const { state, ready } = useDemoStoreContext(); const [filter, setFilter] = useState<'all' | 'passed' | 'failed'>('all'); const [search, setSearch] = useState(''); const [newest, setNewest] = useState(true); if (!ready) return <div className="loading-state">Loading records…</div>
  const records = useMemo(() => state.records.filter((r) => (filter === 'all' || (filter === 'passed' ? r.passed : !r.passed)) && r.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => newest ? b.date.localeCompare(a.date) : a.date.localeCompare(b.date)), [state.records, filter, search, newest]); const passed = state.records.filter((r) => r.passed).length
  return <div className="manager-page wrap"><div className="page-heading"><div><p className="eyebrow">Overview</p><h1>Training records</h1></div><span className="demo-badge">Demo data</span></div><div className="summary-row"><div><span>Total</span><strong>{state.records.length}</strong></div><div><span>Passed</span><strong>{passed}</strong></div><div><span>Failed</span><strong>{state.records.length - passed}</strong></div></div><div className="table-controls"><div className="filter-group" role="group" aria-label="Filter results">{(['all', 'passed', 'failed'] as const).map((item) => <button key={item} className={filter === item ? 'filter active' : 'filter'} onClick={() => setFilter(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}</div><label className="search-box"><span className="sr-only">Search by name</span><Search /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by name" /></label></div>{records.length ? <div className="records-table" role="table"><div className="table-head" role="row"><span>Name</span><span>Score</span><button onClick={() => setNewest(!newest)} aria-sort={newest ? 'descending' : 'ascending'}>Date <ChevronDown /></button><span>Result</span></div>{records.map((record) => <div className={record.learner ? 'table-row learner-row' : 'table-row'} role="row" key={`${record.name}-${record.date}`}><span className="name-cell">{record.name}{record.learner && <em>You</em>}</span><span>{record.score}%</span><span>{formatDate(record.date)}</span><span className={record.passed ? 'status pass' : 'status fail'}>{record.passed ? <Check /> : <X />} {record.passed ? 'Passed' : 'Failed'}</span></div>)}</div> : <div className="empty-state"><p>No records match.</p><button className="button secondary" onClick={() => { setFilter('all'); setSearch('') }}>Clear filters</button></div>}</div>
}
